### ISSUE TITLE
if no instance exist grey out explore action or do not display this option

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swa-teaching/Algernon-Launcher#27] opened 2016-07-12 08:22 UTC
As a user I don't want to see options that are not available/applicable in order to get a clearer overview of what I can actually do.

# Acceptance Criteria
- [ ] make visivle that options are unavailable (or don't show them at all)

**Comment by BenBals** [comment] 2020-08-06 10:11
Duplicate of #55

**Closed as completed by BenBals** 2020-08-06 10:11 UTC
Labels: enhancement
